name: CI
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  python-checks:
    name: Python Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check Ruff format
        uses: astral-sh/ruff-action@v3
      - name: Run doctest
        run: python3 -m doctest -f mhue.py
